/* eslint-disable */
// AUTO-GENERATED BY scripts/generate-embedded-ui.ts — DO NOT EDIT MANUALLY.
//
// This module maps HTTP paths (e.g. "/index.html", "/assets/foo-abc.js") to
// Bun's virtual-filesystem handles for embedded assets. It's populated by
// `bun run scripts/generate-embedded-ui.ts` as part of the `build:binary`
// pipeline and reset to an empty stub after `bun build --compile` runs.
//
// Runtime lookup happens in `tryServeStatic` in ./index.ts — the embedded
// map is consulted first (compiled-binary path) and falls through to the
// real filesystem at `packages/ui/dist/` when empty (dev mode).
//
// Committing the empty stub to git is deliberate: it keeps `bun test` /
// `bun run typecheck` green without forcing a UI build first.

export const EMBEDDED_UI: Record<string, string> = {};
