#!/usr/bin/env bun
/**
 * Generator for `packages/server/src/embedded-ui.gen.ts`.
 *
 * Walks `packages/ui/dist/` recursively and writes out a TypeScript module
 * containing one `with { type: "file" }` import per file, plus a lookup map
 * keyed by HTTP path (e.g. `/index.html`, `/assets/foo-abc.js`). The generated
 * module is imported by `startServer` in `packages/server/src/index.ts` and
 * consulted before the filesystem when serving static assets — dev mode gets
 * the empty stub + filesystem, compiled binary gets the populated map +
 * `$bunfs/` virtual paths.
 *
 * Usage:
 *   bun run scripts/generate-embedded-ui.ts           # populate from dist/
 *   bun run scripts/generate-embedded-ui.ts --empty   # reset to empty stub
 *
 * The `build:binary` npm script runs this tool twice: once to populate
 * before `bun build --compile`, and once with `--empty` after to keep the
 * repo clean between builds.
 */

import { readdir, writeFile } from "node:fs/promises";
import { join, relative, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const DIST_DIR = resolve(REPO_ROOT, "packages/ui/dist");
const OUTPUT_PATH = resolve(
  REPO_ROOT,
  "packages/server/src/embedded-ui.gen.ts",
);

const HEADER = `/* eslint-disable */
// AUTO-GENERATED BY scripts/generate-embedded-ui.ts — DO NOT EDIT MANUALLY.
//
// This module maps HTTP paths (e.g. "/index.html", "/assets/foo-abc.js") to
// Bun's virtual-filesystem handles for embedded assets. It's populated by
// \`bun run scripts/generate-embedded-ui.ts\` as part of the \`build:binary\`
// pipeline and reset to an empty stub after \`bun build --compile\` runs.
//
// Runtime lookup happens in \`tryServeStatic\` in ./index.ts — the embedded
// map is consulted first (compiled-binary path) and falls through to the
// real filesystem at \`packages/ui/dist/\` when empty (dev mode).
//
// Committing the empty stub to git is deliberate: it keeps \`bun test\` /
// \`bun run typecheck\` green without forcing a UI build first.
`;

const STUB_BODY = `
export const EMBEDDED_UI: Record<string, string> = {};
`;

async function walk(dir: string, out: string[] = []): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(full, out);
    } else if (entry.isFile()) {
      out.push(full);
    }
  }
  return out;
}

function writeStub(): string {
  return HEADER + STUB_BODY;
}

async function writePopulated(): Promise<{ content: string; count: number }> {
  const files = (await walk(DIST_DIR)).sort();
  if (files.length === 0) {
    throw new Error(
      `No files found under ${DIST_DIR}. Run \`bun --filter @relay/ui build\` first.`,
    );
  }

  const imports: string[] = [];
  const mapEntries: string[] = [];

  files.forEach((absPath, idx) => {
    // Import path is resolved from packages/server/src/embedded-ui.gen.ts.
    // That file lives one directory deeper than packages/server/, so going
    // up two levels lands at packages/, and packages/ui/dist/<file> is the
    // final target.
    const rel = relative(DIST_DIR, absPath).replace(/\\/g, "/");
    const importPath = `../../ui/dist/${rel}`;
    const httpPath = `/${rel}`;
    imports.push(`import _${idx} from "${importPath}" with { type: "file" };`);
    mapEntries.push(`  "${httpPath}": _${idx},`);
  });

  const content =
    HEADER +
    `//\n// POPULATED: ${files.length} embedded assets from ${DIST_DIR}.\n` +
    `// Run \`bun run scripts/generate-embedded-ui.ts --empty\` to reset.\n\n` +
    imports.join("\n") +
    "\n\nexport const EMBEDDED_UI: Record<string, string> = {\n" +
    mapEntries.join("\n") +
    "\n};\n";

  return { content, count: files.length };
}

async function main(): Promise<void> {
  const isEmpty = process.argv.includes("--empty");

  if (isEmpty) {
    await writeFile(OUTPUT_PATH, writeStub(), "utf-8");
    console.log(`Reset ${relative(REPO_ROOT, OUTPUT_PATH)} to empty stub.`);
    return;
  }

  const { content, count } = await writePopulated();
  await writeFile(OUTPUT_PATH, content, "utf-8");
  console.log(
    `Generated ${relative(REPO_ROOT, OUTPUT_PATH)} with ${count} embedded assets.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
